CREATE TABLE messages (
    id         BIGINT        GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    chat_id    BIGINT        NOT NULL,
    sender_id  BIGINT        NOT NULL,
    content    VARCHAR(2000) NOT NULL,
    created_at TIMESTAMPTZ   NOT NULL,
    read_at    TIMESTAMPTZ,
    CONSTRAINT fk_messages_chat FOREIGN KEY (chat_id) REFERENCES chats (id) ON DELETE CASCADE,
    CONSTRAINT fk_messages_sender FOREIGN KEY (sender_id) REFERENCES users (id),
    CONSTRAINT ck_messages_content_not_blank CHECK (length(trim(content)) > 0)
);

-- Historico paginado por cursor (chat_id + id) e ultima mensagem de cada conversa.
CREATE INDEX idx_messages_chat_id_id ON messages (chat_id, id);
